### ISSUE TITLE
Great Project. I am a newbie.

### ISSUE THREAD

**Issue by osivaz61** [sihaoevery/TaT-ImageNet#5]
I want to know the following question:

Do you train teacher and student models simultaneously or one after the other?

**Comment by sihaoevery** [comment]
Hi,

We grab the pre-trained teacher model from Pytorch and keep it fixed during training for the consideration of reproducibility.
However, training a teacher model on your own for subsequent distillation is also viable.

**Comment by sihaoevery** [comment]
I would safely close this issue. Feel free to reopen it or create one.
